# Default values for siterm-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace to deploy into.
namespace: opennsa

# Deployment Type:
# Available Options are:
#    Deployment - Deploy on one specific node
#    DaemonSet - Deploy on all available nodes
deploymentType: Deployment

# Image to run.
# latest - Production release
# dev - Development release
image:
  image: sdnsense/site-agent-sense:dev
  pullPolicy: Always

# Resources for Agent. This should not require any changes.
# Defaults below:
resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 1
    memory: 3Gi

# SiteRM Agent requires privileges to create vlan interfaces
# and it requires NET_ADMIN capabilities.
securityContext:
  capabilities:
    add:
      - NET_ADMIN

# tolerations for your deployment. Include as many as you need and it will
# be added to your deployment file.
# tolerations:
#   - key: "key"
#     operator: "Equal|Exists"
#     value: "value"
#     effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

# Node Selector for your deployment. Required to set if deploymentType is Deployment:
nodeSelector: node-2-7.sdsc.optiputer.net
# In case of DaemonSet - it will be ignored.

# Configuration parameters for Agent(s):
# These must be defined and configured here: https://github.com/sdn-sense/rm-configs
sitename: T2_US_SDSC
gitrepo: "sdn-sense/rm-configs"
branch: master
# NOTE: In case deploymentType is DaemonSet - comment out md5 line;
#       In DaemonSet deployment agent looks automatically for md5 using hostname
#       and md5 defined here will not be used.
#
#       If deploymentType is Deployment - uncomment md5 line and define md5 here.
#       md5 should be defined for a site under <gitrepo>/<branch>
md5: 1a2b3c4d5e6f7g8h9i

# SSL Sertificate parameters:
# It does support getting certificate from cert-manager or
# from files directory inside this chart.
# Set the correct location to hostcert and hostkey inside files directory
# In case of cert manager - set certmanager to true
# and all certmanager related parameters
certmanager: true
certmanager_params:
  commonName: "sense-node-2-7.sdsc.optiputer.net"
  dnsNames:
    - "sense-node-2-7.sdsc.optiputer.net"
#  duration: 720h0m0s
  issuerRef:
#    group: cert-manager.io
    kind: Issuer
    name: sense-issuer
#   renewBefore: 120h0m0s
#  privateKey:
#    algorithm: RSA
#    encoding: PKCS1
#    size: 4096

# If you need to use your own Issuer (e.g. There is no ClusterIssuer) - set it to true.
# Name of issuer must be same as used in certmanager_params:issuerRef:name
# Email address for registering to server (e.g. LetsEncrypt requires that)
# server - remove issue ACME Endpoint.
issuer: true
issuer_params:
  name: sense-issuer
  email: "juztas@gmail.com"
  server: "https://acme-v02.api.letsencrypt.org/directory"

# if certmanager is false - set hostcert and hostkey to true - which
# points to pem files.
#hostcert: "files/hostcert.pem"
#hostkey: "files/hostkey.pem"
