---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: siterm-agent-node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: siterm-agent-read-node-labels
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: siterm-agent-node-reader
  apiGroup: rbac.authorization.k8s.io
